trigger: none
#  branches:
#    include:
#    - main
#  paths:
#    include:
#    - azuredatafactory
    
pool:
  vmImage: 'ubuntu-latest'

variables:
  - group: 'ADF Variable Group'
  - name: workingDir
    value: $(Build.Repository.LocalPath)/azuredatafactory/src
  - name: serviceConnection
    value: 'ADF Deployment Service Connection'
  - name: dataFactoryNameDev
    value: ''
  - name: dataFactoryNameStaging
    value: ''
  - name: dataFactoryNameProd
    value: ''
  - name: resourceGroupName
    value: ''

stages:
  - stage: build
    displayName: 'Build Artifacts'
    jobs:
      - job:
        steps:
        # configuring node
        - task: NodeTool@0
          inputs:
            versionSpec: '14.x'
          displayName: 'Install Node.js'

        - task: Npm@1
          inputs:
            command: 'install'
            verbose: true
            workingDir: '$(workingDir)'
          displayName: 'Install npm package'

        # validating artifacts
        - task: Npm@1
          inputs:
            command: 'custom'
            customCommand: 'run build validate $(workingDir) /subscriptions/$(subscriptionId)/resourceGroups/$(resourceGroupName)/providers/Microsoft.DataFactory/factories/$(dataFactoryNameDev)'
            workingDir: '$(workingDir)'
          displayName: 'Validate'

        # generating ARM Templates from source code
        - task: Npm@1
          inputs:
            command: 'custom'
            customCommand: 'run build export $(workingDir) /subscriptions/$(subscriptionId)/resourceGroups/$(resourceGroupName)/providers/Microsoft.DataFactory/factories/$(dataFactoryNameDev) artifacts'
            workingDir: '$(workingDir)'
          displayName: 'Generate ARM template'

        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(workingDir)/artifacts'
            Contents: '**'
            TargetFolder: '$(build.artifactstagingdirectory)/application' 
          displayName: 'Copying application artifact'

        - task: CopyFiles@2
          inputs:
            SourceFolder: '$(Build.Repository.LocalPath)/azuredatafactory/cicd-parameters'
            Contents: '*.json'
            TargetFolder: '$(build.artifactstagingdirectory)/ARMTemplateParameter' 
          displayName: 'Copying CICD ARM Template Parameter Files'

        - task: PublishPipelineArtifact@1
          inputs:
            targetPath: '$(build.artifactstagingdirectory)'
            artifact: 'datafactory'
            publishLocation: 'pipeline'

  - stage: 'development'
    displayName: 'Development deploy'
    dependsOn: build
    variables:
      dataFactoryName: $(dataFactoryNameDev)
    jobs: 
    - deployment: DeployToDevelopment
      pool:
        vmImage: 'windows-latest'
      environment: development 
      strategy:
        runOnce:
          deploy:
            steps:
              - task: DownloadPipelineArtifact@2 #downloading artifacts created in build stage
                inputs:
                  source: 'current'
                  path: '$(Pipeline.Workspace)'

              - task: AzureResourceManagerTemplateDeployment@3
                displayName: 'Deploying ADF Artificats'
                inputs:
                  deploymentScope: 'Resource Group'
                  azureResourceManagerConnection: '$(serviceConnection)'
                  subscriptionId: $(subscriptionId)
                  action: 'Create Or Update Resource Group'
                  resourceGroupName: '$(resourceGroupName)'
                  location: 'eastus'
                  templateLocation: 'Linked artifact'
                  csmFile: '$(Pipeline.Workspace)/datafactory/application/ARMTemplateForFactory.json'
                  csmParametersFile: '$(Pipeline.Workspace)/datafactory/ARMTemplateParameter/ARMTemplateParams-Dev.json'
                  deploymentMode: 'Incremental'

  - stage: 'staging'
    displayName: 'Staging deploy'
    dependsOn: development
    variables:
      dataFactoryName: $(dataFactoryNameStaging)
    jobs: 
    - deployment: DeployToStaging
      pool:
        vmImage: 'windows-latest'
      environment: staging 
      strategy:
        runOnce:
          deploy:
            steps:
              - task: DownloadPipelineArtifact@2 #downloading artifacts created in build stage
                inputs:
                  source: 'current'
                  path: '$(Pipeline.Workspace)'
              - task: AzureResourceManagerTemplateDeployment@3
                displayName: 'Deploying ADF Artificats'
                inputs:
                  deploymentScope: 'Resource Group'
                  azureResourceManagerConnection: '$(serviceConnection)'
                  subscriptionId: $(subscriptionId)
                  action: 'Create Or Update Resource Group'
                  resourceGroupName: '$(resourceGroupName)'
                  location: 'eastus'
                  templateLocation: 'Linked artifact'
                  csmFile: '$(Pipeline.Workspace)/datafactory/application/ARMTemplateForFactory.json'
                  csmParametersFile: '$(Pipeline.Workspace)/datafactory/ARMTemplateParameter/ARMTemplateParams-Staging.json'
                  deploymentMode: 'Incremental'

  - stage: prod
    displayName: Production deploy
    dependsOn: staging
    variables:
      dataFactoryName: $(dataFactoryNameProd)
    jobs: 
    - deployment: DeployToProd
      pool:
        vmImage: windows-latest
      environment: production
      strategy:
        runOnce:
          deploy:
            steps:
              - task: DownloadPipelineArtifact@2 #downloading artifacts created in build stage
                inputs:
                  source: 'current'
                  path: '$(Pipeline.Workspace)'
              
              - task: AzureResourceManagerTemplateDeployment@3
                displayName: 'Deploying ADF Artificats'
                inputs:
                  deploymentScope: 'Resource Group'
                  azureResourceManagerConnection: '$(serviceConnection)'
                  subscriptionId: $(subscriptionId)
                  action: 'Create Or Update Resource Group'
                  resourceGroupName: '$(resourceGroupName)'
                  location: 'eastus'
                  templateLocation: 'Linked artifact'
                  csmFile: '$(Pipeline.Workspace)/datafactory/application/ARMTemplateForFactory.json'
                  csmParametersFile: '$(Pipeline.Workspace)/datafactory/ARMTemplateParameter/ARMTemplateParams-Prod.json'
                  deploymentMode: 'Incremental'