name: 'Called ADF Deploy Action'
description: 'This action deploys the ARM template for Azure Data Factory'

inputs:
  resource-group-name:
    description: 'The name of the resource group'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        enable-AzPSSession: true
