name: 'Called ADF Deploy Action'
description: 'This action deploys the ARM template for Azure Data Factory'

inputs:
  resource-group-name:
    description: 'The name of the resource group'
    required: true
  data-factory-name:
    description: 'The name of the Azure Data Factory'
    required: true
  arm-template-file:
    description: 'The name of the ARM template file'
    required: true
  arm-template-parameters-file:
    description: 'The name of the ARM template parameters file'
    required: true
  azure-credentials:
    description: 'The Azure credentials'
    required: true
  additional-parameters:
    description: 'Addtional Override Parameters for the ARM Template Deployment'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Set current date as env variable
      shell: bash
      run: echo "SASExpiration=$(date --date="tomorrow" +"%Y-%m-%d")" >> $GITHUB_ENV
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ inputs.azure-credentials }}
        enable-AzPSSession: true
          
    - name: Download a single artifact
      uses: actions/download-artifact@v3
      with:
        name: datafactory
        
    - name: 'Create Storage Account for Linked Templates'
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az storage account create --name saadf1512deveus --resource-group ${{ inputs.resource-group-name }}
      
    - name: 'Create Container for Linked Templates'
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az storage container create --name templates --account-name saadf1512deveus
      
    - name: 'Create SAS Token'
      shell: pwsh
      run: |
         $token= az storage container generate-sas --account-name saadf1512deveus --name templates --permissions r --expiry ${{ env.SASExpiration }} --output tsv
         echo "SAS_TOKEN=$token"| Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
    - name: 'Copy Linked Templates to Azure Storage'
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az storage blob upload-batch --account-name saadf1512deveus --destination templates --source ${{ github.workspace }}
         
    - name: Install Az PowerShell module
      run: if('${{ inputs.skipAzModuleInstallation }}' -ne 'true') { Install-Module -Name Az -Scope CurrentUser -Repository PSGallery -Force }
      shell: pwsh

    - name: Run Pre-deployment script
      run: |
        ${{ github.workspace }}/PrePostDeploymentScript.ps1 `
          -armTemplate ${{github.workspace}}'/linkedTemplates/ArmTemplate_master.json' `
          -ResourceGroupName "${{ inputs.resource-group-name }}" `
          -DataFactoryName "${{ inputs.data-factory-name }}" `
          -predeployment $true `
          -deleteDeployment $false
      shell: pwsh
      
    - name: Deploy ARM Template
      uses: azure/CLI@v1
      with:
        inlineScript: |
           az deployment group create --resource-group ${{ inputs.resource-group-name }} --template-uri ${{ format('{0}?{1}', 'https://saadf1512deveus.blob.core.windows.net/templates/linkedTemplates/ArmTemplate_master.json',env.SAS_TOKEN) }} --parameters ${{ format('{0}/{1}?{2}', 'https://saadf1512deveus.blob.core.windows.net/templates/datafactory/cicd-parameters', inputs.arm-template-parameters-file, env.SAS_TOKEN) }}
          # az deployment group create --resource-group ${{ inputs.resource-group-name }} --template-uri ${{ format('{0}?{1}', 'https://saadf1512deveus.blob.core.windows.net/templates/linkedTemplates/ArmTemplate_master.json',env.SAS_TOKEN) }} --parameters ${{ format('{0}/{1}?{2}', 'https://saadf1512deveus.blob.core.windows.net/templates/datafactory/cicd-parameters', inputs.arm-template-parameters-file, env.TEST_TOKEN) }}
   # - name: Run ARM deploy
   #  uses: azure/arm-deploy@v1
   #   with:
   #     resourceGroupName: ${{ inputs.resource-group-name }}
   #     template:  ${{ format('{0}?{1}', 'https://saadf1512deveus.blob.core.windows.net/templates/linkedTemplates/ArmTemplate_master.json',env.SAS_TOKEN) }}
   #    parameters: ${{ format('{0}/{1}?{2}', 'https://saadf1512deveus.blob.core.windows.net/templates/datafactory/cicd-parameters', inputs.arm-template-parameters-file, env.SAS_TOKEN) }}
        
    - name: Run Post-deployment script
      run: |
         ${{ github.workspace }}/PrePostDeploymentScript.ps1 `
          -armTemplate ${{github.workspace}}'/linkedTemplates/ArmTemplate_master.json' `
          -ResourceGroupName "${{ inputs.resource-group-name }}" `
          -DataFactoryName '${{ inputs.data-factory-name }}' `
          -predeployment $false `
      shell: pwsh
   
    - name: 'Delete Storage Account for Linked Templates'
      uses: azure/CLI@v1
      with:
        inlineScript: |
         az storage account delete --name saadf1512deveus --resource-group ${{ inputs.resource-group-name }} --yes

    - name: Azure CLI script
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az logout
          az cache purge
          az account clear
