name: 'Caller ADF Build and Deploy Example'

on:
  workflow_dispatch:
#  push:
#    branches:
#      - main
#  pull_request:

env:
  workingDir: 'azuredatafactory/src/'
  workingDirARMParameters: 'azuredatafactory/cicd-parameters/'
  dataFactoryNameDev: 'adf-demo-dev-eastus-001'
  dataFactoryNameStaging: 'adf-demo-staging-eastus-001'
  dataFactoryNameProd: 'adf-demo-prod-eastus-001'
  resourceGroupName: 'rg-datafactory-demo'

jobs:
  build-adf-arm-templates:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - uses: actions/checkout@v3
      - id: foo
        uses: ./.github/actions/adf-build
        with:
          adf-environment: development
          adf-name: ${{ env.dataFactoryNameDev }}
          resource-group-name: ${{ env.resourceGroupName }}
          working-directory: '${{ github.workspace }}/${{ env.workingDir }}'
          working-directory-arm-parameters: '${{ github.workspace }}/${{ env.workingDirARMParameters }}'
          subscription-id: ${{ secrets.AZURE_ADF_SUBSCRIPTIONID }}
