name: 'Azure Data Factory Deployment'

on:
  workflow_dispatch:
#  push:
#    branches:
#      - main
#  pull_request:

jobs:
  adf-cicd:
    runs-on: ubuntu-latest

    env:
      workingDir: '/azuredatafactory/src'
      dataFactoryNameDev: 'adf-cicd-jtf-dev'
      dataFactoryNameStaging: 'adf-cicd-jtf-staging'
      dataFactoryNameProd: 'adf-cicd-jtf-prod'
      resourceGroupName: 'rg-datafactory-demo'

    steps:
      # We'll need to check out the repository so that we can build the ADF ARM Template
      - name: Checkout
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'
          
      - name: Echo variable contents
        run: echo "GitHub WorkSpace = $GITHUB_WORKSPACE"
          
      - name: Echo GitHub Workspace data factory contents
        run: ls '${{ github.workspace }}/azuredatafactory/src'
          
      - name: Echo GitHub Workspace contents
        run: ls '${{ github.workspace }}'
      
      - name: Install npm package
        working-directory: '${{ github.workspace }}/azuredatafactory/src'
        run: npm install
          
      - name: Echo GitHub Workspace contents after npm package installation
        run: ls '${{ github.workspace }}'

      - name: Validate
        working-directory: '${{ github.workspace }}/azuredatafactory/src'
        run: npm run build validate '${{ github.workspace }}/azuredatafactory/src' '/subscriptions/${{ secrets.AZURE_ADF_SUBSCRIPTIONID }}/resourceGroups/${{ env.resourceGroupName }}/providers/Microsoft.DataFactory/factories/${{ env.dataFactoryNameDev }}'

      - name: Generate ARM template
        working-directory: '${{ github.workspace }}/azuredatafactory/src'
        run: npm run build export '${{ github.workspace }}/azuredatafactory/src' '/subscriptions/${{ secrets.AZURE_ADF_SUBSCRIPTIONID }}/resourceGroups/${{ env.resourceGroupName }}/providers/Microsoft.DataFactory/factories/${{ env.dataFactoryNameDev }}'

      - name: Copying application artifact
        run: Copy '${{ github.workspace }}/artifacts/**' '${{ github.workspace }}/application'

      - name: Copying CICD ARM Template Parameter Files
        run: Copy '${{ github.workspace }}/azuredatafactory/cicd-pipeline/*.json' '${{ github.workspace }}/ARMTemplateParameter'

#      - name: Build bicep artifact
#        uses: azure/cli@v1.0.0
#        with:
#          inlineScript: 
#            $file = "${{ github.workspace }}/azuredatafactory/iac/datafactory.bicep"            
#            New-Item -ItemType Directory -Force -Path ${{ github.workspace }}/infrastructure
#            az bicep build --file $file --outdir ${{ github.workspace }}/infrastructure
#          azcliversion: latest

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          path: ${{ github.workspace }}

