name: 'Caller ADF Build and Deploy Example'

on:
  workflow_dispatch:
#  push:
#    branches:
#      - main
#  pull_request:

env:
  adfdevelopmentenvironment: 'development'
  workingDir: 'azuredatafactory/src/'
  workingDirARMParameters: 'azuredatafactory/cicd-parameters/'
  arm-template-file: 'azuredatafactory/linkedTemplatesARMTemplate_master.json'
  dataFactoryNameDev: 'adf-github-dev-eus'
  resourceGroupName: 'rg-github-dev-eus'

jobs:
  job-build-adf-arm-template:
    runs-on: ubuntu-latest
    name: build-adf-arm-template
    steps:
      - uses: actions/checkout@v3
        
      - id: adf-build
        uses: ./.github/actions/adf-build
        with:
          adf-environment: ${{ env.adfdevelopmentenvironment }}
          adf-name: ${{ env.dataFactoryNameDev }}
          resource-group-name: ${{ env.resourceGroupName }}
          working-directory: '${{ github.workspace }}/${{ env.workingDir }}'
          working-directory-arm-parameters: '${{ github.workspace }}/${{ env.workingDirARMParameters }}'
          subscription-id: ${{ secrets.AZURE_ADF_SUBSCRIPTIONID }}
          
  job-deploy-adf-arm-template:
    runs-on: ubuntu-latest
    name: deploy-adf-arm-template
    needs: job-build-adf-arm-template
    environment: development
    steps:
      - uses: actions/checkout@v3
        
      - id: adf-deployment
        uses: ./.github/actions/adf-deploy-linkedtemplate
        with: 
          resource-group-name: ${{ env.resourceGroupName }}
          data-factory-name: ${{ env.dataFactoryNameDev }}
          arm-template-file: ${{ env.arm-template-file }}
          arm-template-parameters-file: 'ARMTemplateParams-Dev.json'
          azure-credentials: ${{ secrets.AZURE_CREDENTIALS }}
