name: 'Called ADF Deploy Workflow'

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      AZURE_CREDENTIALS:
        required: true

jobs:
  reuseable-adf-deploy-job:
    runs-on: ubuntu-latest
    needs: build-adf-arm-templates
    environment: development
    steps:    
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true