name: Reusable ADF Deploy Workflow Example

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  reuseable-adf-deploy-job:
    runs-on: ubuntu-latest